### ISSUE TITLE
record into buffer first and write later

### ISSUE THREAD

**Issue by tkleiner** [janscience/TeeRec#1]
This is not an issue but a question. How do I need to configure ADC and SD writer to record into the buffer until the buffer is full and then write to SD card to avoid noise coupling from SD card into the signal path?   

In [SDWriter.cpp](https://github.com/janscience/TeeRec/blob/main/src/SDWriter.cpp) I found, that writing to an SD card is set up to happen after 1/4 of the buffer is filled. It is possible to calculate the time that is needed for a given sample rate to fill 1/4 of the buffer and use `file.setMaxFileTime(settings.FileTime);` in e.g. [recorder.ino](https://github.com/janscience/TeeRec/blob/main/examples/recorder/recorder.ino). But I am not sure if this is the way to go. 

I am aiming at a recorder-like application where a recording starts after a trigger (push button or external interrupt) that stops automatically when the buffer is full and then stores the raw data (buffer) to the SD card. Some processing of the data in the buffer will be done in the time until the next trigger. I have look also into  pedvide/ADC and EOD-Logger.  

Very nice project.

**Comment by janscience** [comment]
Thank you for your question. Yes, those SD write artifacts are annoying. The main idea of the TeeRec library is for continuous acquisition and writing (including the artifacts....). In contrast to Paul Stoffregen's great audio library (https://github.com/PaulStoffregen/Audio) TeeRec can handle arbitrary sampling rates and has this single big cyclic data buffer. If I understand you correctly you want to run the ADC and at the moment when you press a pushbutton you want to save the full buffer content into a file. You could tweak  examples/logger/logger.ino to achieve this:
Change setupStorage() to
```
void setupStorage() {
  file.dataDir(settings.Path);
  file.setMaxFileTime(0);   // setting this to zero is very important! To make writeData actually write the data.
}
```
Remove storeData() from loop(). Instead you need to check for your event. If the event happens you should run some code like this:

```
aidata.stop();
file.startWrite();   // Sets write position to current end of buffer
file.TailCycle--;    // You want to start writing a full cycle before!
char dts[20];
rtclock.dateTime(dts);
file.openWave(name.c_str(), aidata, -1, dts);
file.writeData();
file.close();
aidata.start();   // Restart data acquisition
```
Unfortunately, `DataConsumer::TailCycle` (in DataBuffer.h) is protected. So decrementing `TailCycle` is not possible. Add a new function to `SDWriter` that works exactly like `SDWriter::startWrite()` but also decrements `TailCycle`. Then it should work.

**Comment by tkleiner** [comment]
Thank you! I felt a little uncomfortable by opening an issue for a question. Is there another/better way to ask questions?

**Comment by janscience** [comment]
That's fine.

I reworked a bit the data producer/consumer model. Now the SDWriter::startWrite() function has an optional argument that lets you set the start point for saving n samples before the current position. The first three lines of my suggestion above should look like:
```
aidata.stop();
file.startWrite(n);
```
where `n` is the number of samples to go back.
